terraform-ibm-modules/terraform-ibm-base-ocp-vpc

main.tf
tests/other_test.go
tests/pr_test.go

This change is to unblock the upgrade test which were failing earlier due to some changes in `main.tf`
Test Change - Upgrade test is also included now, which was not part of `pr_tests.go` earlier.
---
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

tests: Unblocking upgrade test

---

main.tf
module-metadata.json

update comment in code around apikey reset workaround
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

fix: update comment in code around apikey reset workaround

---

module-metadata.json
variables.tf

Add validation block on ocp_version variable
issue:  https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/63
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

add_validation_block_in_ocp_version

---

README.md
module-metadata.json
version.tf

update version.tf to use range
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new …

fix: update version.tf to use range

---

.secrets.baseline
main.tf
module-metadata.json

Addons creation timing out because it was trying to install the pods before the workers are available.
```
TestRunCompleteExample/4.12 2023-05-12T05:37:31Z logger.go:66: │ Error: [ERROR] Error waiting for Addon to reach normal during create () : timeout while waiting for state to become 'normal, warning, critical, available' (timeout: 20m0s)
TestRunCompleteExample/4.12 2023-05-12T05:37:31Z logger.go:66: │ 
TestRunCompleteExample/4.12 2023-05-12T05:37:31Z logger.go:66: │   with module.ocp_all_inclusive.module.ocp_base.ibm_container_addons.addons,
TestRunCompleteExample/4.12 2023-05-12T05:37:31Z logger.go:66: │   on .terraform/modules/ocp_all_inclusive.ocp_base/main.tf line 360, in resource "ibm_container_addons" "addons":
TestRunCompleteExample/4.12 2023-05-12T05:37:31Z logger.go:66: │ …
```

fix: add depends on for addon

---

.github/settings.yml
.github/workflows/ci.yml
.github/workflows/release.yml
README.md
cra-tf-validate-ignore-rules.json

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional …

ci: update to pipeline v2

---

main.tf

Increasing the timeout as ocp-all-inclusive examples takes more time for all the deployments to come up.
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Run the CI …

fix: increase the timeout

---

.secrets.baseline
module-metadata.json
tests/pr_test.go
variables.tf
version.tf

Removed 4.9 as well in this PR given that this version is deprecated
fixes #196 
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Run the CI pipeline when the PR is …

feat: add support for ocp 4.13

---

examples/multiple_mzr_clusters/main.tf
main.tf

Add temporary fix to delay the addon creation.
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Run the CI pipeline when the PR is ready for review and you expect tests …

fix: add temporary fix for the addon creation failure

---

examples/standard/main.tf
main.tf
module-metadata.json
variables.tf

update depends_on blocks (see https://github.ibm.com/GoldenEye/issues/issues/5265#issuecomment-60848737)
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.
Run the CI …

fix: update depends_on blocks

---

README.md

add tshoot note in main readme file about ocp version mismatch
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

docs: add issue about version mismatch

---

modules/fscloud/README.md

updated fscloud module readme
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

docs: update fscloud module readme

---

.catalog-onboard-pipeline.yaml
.github/settings.yml
.secrets.baseline
README.md
examples/add_rules_to_sg/catalogValidationValues.json.template
examples/advanced/catalogValidationValues.json.template
examples/basic/catalogValidationValues.json.template
examples/fscloud/catalogValidationValues.json.template
examples/multiple_mzr_clusters/catalogValidationValues.json.template
ibm_catalog.json

Catalog onboard
```
/run pipeline
```

Catalog onboard

---

examples/advanced/main.tf

Issue: https://github.ibm.com/GoldenEye/issues/issues/6967
```
/run pipeline
```

fix: update autoscaler version

---

examples/multiple_mzr_clusters/main.tf

Bump observability agents in mzr example past 1.18.0 which adds and removes inputs on the module. This is in example code so it may not require a release since it does not impact the modules function.
```
/run pipeline
```
- Use the …

fix: bump observability agents with changed inputs

---

README.md
main.tf
scripts/get_config_map_status.sh
scripts/reset_iks_api_key.sh
version.tf

Issue : https://github.ibm.com/GoldenEye/issues/issues/7465
```
/run pipeline
```

fix: increase the wait time

---

scripts/get_config_map_status.sh

fix: Increase the wait time for checking the configmap

---

tests/other_test.go

Create test for custom_sg example
https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/349
Create a test that implements the custom_sg example.
```
/run pipeline
```

tests: add test for custom sg

---

README.md
modules/fscloud/README.md
modules/fscloud/version.tf
version.tf

update version constraints
https://github.ibm.com/GoldenEye/issues/issues/4915
```
/run pipeline
```

chore: update version constraints

---

modules/fscloud/README.md
modules/fscloud/outputs.tf

Issue https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/369
```
/run pipeline
```

fix: add missing output

---

README.md
modules/fscloud/README.md
modules/fscloud/outputs.tf
outputs.tf

updated the description for ingress hostname
issue: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/416
```
/run pipeline
```

feat: update description for ingress hostname

---

cra-tf-validate-ignore-rules.json
examples/advanced/main.tf
examples/fscloud/main.tf
examples/multiple_mzr_clusters/main.tf

NOTE: these are renovate changes, with one addition.
Renovate terraform module upgrades in examples. The upgrade of the VPC module has triggered new CRA scan failures for account level settings, which should be ignored for test pipeline. Have added those rules to ignore file.
```
/run pipeline
```
- Include information that users need to know about the PR in the commit message. …

chore(deps): update terraform-modules

---

main.tf

fix bug around disable_outbound_traffic_protection value
```
/run pipeline
```

fix: fix bug around disable_outbound_traffic_protection value

---

README.md
examples/add_rules_to_sg/version.tf
examples/advanced/version.tf
examples/basic/version.tf
examples/cross_kms_support/version.tf
examples/custom_sg/version.tf
examples/fscloud/version.tf
examples/multiple_mzr_clusters/version.tf
version.tf

chore: update minimum provider version required to 1.66.0

---

examples/advanced/README.md
examples/advanced/main.tf

Fixed advanced example by adding public gateways in all the zones to make the ingress healthcheck to work as expected
Advanced example modified with public gateways in all the zones
```
/run pipeline
```
- Use the **Squash and merge** …

Fixed  advanced example to handle ingress check

---

tests/pr_test.go

fix: increase the wait time for schematics test

---

examples/fscloud/main.tf
examples/multiple_mzr_clusters/main.tf

Currently cloud logs is not supported in most of the region, which is causing the pipeline to fail if the test runs in a region in which cloud logs is not supported.
```
/run pipeline
```

fix: disable cloud_logs provision

---

tests/other_test.go
tests/pr_test.go
variables.tf

Refer Issue: [Issue-10665](https://github.ibm.com/GoldenEye/issues/issues/10665)
* Support added to include ocp version 4.16 
```
/run pipeline
```

feat: added support for ocp v4.16 

---

tests/pr_test.go

Removed AT variable from fscloud example.
```
/run pipeline
```

tests: removed AT variable from fscloud ex

---

main.tf

fix: pass wait_for_apply to the kms_config block

---

scripts/reset_iks_api_key.sh

API result now gives a different status code for apikey creation.
```
/run pipeline
```

fix: add additional status code for apikey creation

---

examples/advanced/main.tf
main.tf
tests/other_test.go
tests/pr_test.go
variables.tf

chore: remove support for 4.12 and 4.13 ocp versions

---

README.md
examples/add_rules_to_sg/version.tf
examples/advanced/version.tf
examples/basic/main.tf
examples/basic/version.tf
examples/cross_kms_support/version.tf
examples/custom_sg/version.tf
examples/fscloud/README.md
examples/fscloud/main.tf
examples/fscloud/version.tf
examples/multiple_mzr_clusters/main.tf
examples/multiple_mzr_clusters/version.tf
main.tf
modules/fscloud/README.md
modules/fscloud/main.tf
modules/fscloud/variables.tf
modules/fscloud/version.tf
tests/other_test.go
tests/pr_test.go
variables.tf
version.tf

add support for `orphan_on_delete` to handle the default worker error 
```
The action cannot be completed because it would reduce the worker pool's size below the cluster's minimum requirement of 2 workers. If there are any worker operations pending, you might need wait for them to complete.
```
```
/run pipeline
```
- Include information that users need to know about the PR in …

feat: add support for `orphan_on_delete` for default worker pool

---

main.tf

issue: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/617
```
/run pipeline
```

fix: use user provided version of `vpc-block-csi-driver`

---

solutions/fully-configurable/catalogValidationValues.json.template

use unique prefix in catalog validation to avoid name clash

---

ibm_catalog.json

added compliance profile in ibm_catalog.json
issue: https://github.ibm.com/GoldenEye/issues/issues/13242
This PR add compliance profile in ibm_catalog.json.
```
/run pipeline
```

feat: added compliance profile in ibm_catalog.json

---

ibm_catalog.json

fix: made `kms_endpoint_type` a dropdown in DA

---

ibm_catalog.json

Catalog validation failing with internal error in schematics,so reverting UI regex validation
This PR is to revert UI regex validation.
```
/run pipeline
```

Reverted UI regex validation

---

solutions/fully-configurable/variables.tf

change default OS in DA to RHCOS
```
/run pipeline
```

feat: change default OS in DA to RHCOS

---

solutions/fully-configurable/variables.tf

https://github.ibm.com/GoldenEye/issues/issues/15651
Fix regex validation to enforce exact match (public or private)

chore: fix regex validation to enforce exact match (public or private) 

---

.catalog-onboard-pipeline.yaml
ibm_catalog.json

fix: Remove "compliance" from quickstart DA

---

ibm_catalog.json

Updated variation label to include the word "Experimental" until end to end flow is more user friendly. No release needed for this as the version currently published in prod is already updated
```
/run pipeline
```
- Use the **Squash and …

chore: Add Experimental to the fully configurable variation

---

ibm_catalog.json

docs: update quickstart doc
