- examples/apply_taints/README.md
- examples/apply_taints/main.tf
- examples/apply_taints/variables.tf
- main.tf
- module-metadata.json
Added a count = var.verify_worker_network_readiness ? 1 : 0 on that data block and creating a private-only cluster in the apply_taints example which runs a test in the other_tests.
Ref: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/68#issuecomment-1479910490
Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.
---
The commit message determines whether a new version of the module is needed, …
> fix: add count to the data block

- .gitignore
- cra-tf-validate-ignore-goals.json
- main.tf
- module-metadata.json
In order to retrieve coherent information from IKS API about available versions within the same region where the cluster is going to be created the ibm_container_cluster_versions data source is now using the region 
In addiction I added the resource group id as it is expected to reduce the response time on IKS API according to the API specs.
https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/159
More info available at (https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/159)
---
The commit message determines whether a new version of the …
> feat: added region and res group id when collecting available versions

- main.tf
- module-metadata.json
In terraform-ibm-base-ocp-vpc the block data.ibm_container_cluster_versions region is now deprecated. 
https://github.ibm.com/GoldenEye/issues/issues/4969
The region from the data block ibm_container_cluster_versions has been removed since it was deprecated. As per the provider doc if the region is not specified it will be defaulted to the provider region.
If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the …
> fix: cluster version region

- README.md
- examples/add_rules_to_sg/version.tf
- examples/apply_taints/version.tf
- examples/existing_cos/version.tf
- examples/fscloud/version.tf
- examples/multiple_mzr_clusters/version.tf
- examples/single_zone_autoscale_cluster/version.tf
- examples/standard/version.tf
- main.tf
- module-metadata.json
- modules/fscloud/README.md
- modules/fscloud/version.tf
- version.tf
Update the version of the csi-driver and set a upper limit on the terraform version.
```
/run pipeline
```
- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> fix: limit the terraform version

- tests/other_test.go
- tests/pr_test.go
- variables.tf
Update OCP related modules to only support the following versions: 4.12, 4.13, 4.14
```
/run pipeline
```
> feat: add support for OCP 4.14

- README.md
- examples/fscloud/main.tf
- main.tf
Upgrade `terraform-ibm-cos` module to the latest version of v8.2.6.
Minor change needed for this upgrade, removed parameter `create_resource_key` for the COS module as that input has been removed. Did not need to be replaced as it was set to `false`.
Upgraded `terraform-ibm-cos` module to the latest version of v8.2.6.
```
/run pipeline
```
- Include information that users need …
> fix: upgrade cos module to latest

- main.tf
Added changes to inlcude operating system for pools.
Refer [Issue-460](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/460)
```
/run pipeline
```
> feat: added operating_system for pools

- README.md
> docs: clarify readme doc

- tests/other_test.go
- tests/pr_test.go
Issue: https://github.ibm.com/GoldenEye/issues/issues/10743
```
/run pipeline
```
> fix: add the default pool workaround to other test

- main.tf
Fix [Issue 523](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/523)
* fix: additional security groups will be used when creating autoscaled worker pools
```
/run pipeline
```
- Use the **Squash and merge** …
> fix: additional security groups for autoscaling worker pools

- tests/pr_test.go
This PR attempts to fix the [issue-536](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/536)
```
/run pipeline
```
> test: modified implicitdestroy field to avoid errors in pipeline logs

- tests/pr_test.go
```
[31m│[0m [0m[1m[31mError: [0m[0m[1mRequest failed with status code: 400, ServerErrorResponse: {"incidentID":"3ec0a1f7-10d2-4175-babf-f41a92587785,3ec0a1f7-10d2-4175-babf-f41a92587785","code":"E1437","description":"The action cannot be completed because it would reduce the worker pool's size below the cluster's minimum requirement of 2 workers. If there are any worker operations pending, you might need wait for them to complete.","type":"BadRequest"}[0m
[31m│[0m [0m
[31m│[0m [0m[0m---
[31m│[0m [0mid: terraform-74d077da
[31m│[0m [0msummary: 'Request failed with status code: 400, ServerErrorResponse:
[31m│[0m [0m{"incidentID":"3ec0a1f7-10d2-4175-babf-f41a92587785,3ec0a1f7-10d2-4175-babf-f41a92587785","code":"E1437","description":"The
[31m│[0m [0m  action …
```
> test: add ImplicitDestroy for default pool

- README.md
- scripts/confirm_lb_active.sh
- scripts/reset_iks_api_key.sh
Update the script to use the respective endpoint  env variable to create the api endpoint.
```
/run pipeline
```
> fix: update the script to use respective endpoint variable

- main.tf
- scripts/enable_disable_ocp_console.sh
Updated the script by removing exponential backoff time and scoping the retry_wait time to respective functions.
Issue - #599
```
/run pipeline
```
> fix: modified retry logic issue

- main.tf
```
resource "null_resource" "ocp_console_management" {
depends_on = [null_resource.confirm_network_healthy]
triggers = {
enable_ocp_console = var.enable_ocp_console
}
provisioner "local-exec" {
command     = "${path.module}/scripts/enable_disable_ocp_console.sh"
interpreter = ["/bin/bash", "-c"]
environment = {
KUBECONFIG         = data.ibm_container_cluster_config.cluster_config[0].config_file_path
ENABLE_OCP_CONSOLE = var.enable_ocp_console
}
}
}
```
The `ocp_console_management` block requires `ibm_container_cluster_config.cluster_config` but it used to only run if network_readiness was set to true of if we were to install cluster_autoscaler. If these condition was false `ibm_container_cluster_config.cluster_config` wouldn't run and it would cause the `ocp_console_management` to fail …
> fix: run cluster_config for ocp_console_management

- ibm_catalog.json
updated kms add-on mapping
issue: https://github.ibm.com/GoldenEye/issues/issues/13413
```
/run pipeline
```
> fix: updated kms add-on mapping

- tests/other_test.go
In the advanced example we are not installing obs agents, so we need to ignore the update to the helm release.
```
/run pipeline
```
> test: ignore logs_agent update in advanced example

- .secrets.baseline
- README.md
- examples/add_rules_to_sg/version.tf
- examples/advanced/version.tf
- examples/basic/version.tf
- examples/cross_kms_support/version.tf
- examples/custom_sg/version.tf
- examples/fscloud/version.tf
- examples/multiple_mzr_clusters/version.tf
- main.tf
- modules/fscloud/README.md
- modules/fscloud/version.tf
- modules/kube-audit/README.md
- modules/kube-audit/version.tf
- solutions/fully-configurable/README.md
- solutions/fully-configurable/version.tf
- tests/other_test.go
- tests/pr_test.go
- version.tf
This is an update to the most recent version of the IBM-Cloud Terraform provider which includes a bug fix to the attach of security groups to a load balancer not in "active" state.
As a result of this provider bug fix, the workaround script in this module to also solve this problem has been removed.
```
/run pipeline
```
- Include information that users need to know about the PR …
> fix: update latest ibmcloud provider version

- scripts/reset_iks_api_key.sh
Issue: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/695
```
/run pipeline
```
> fix: display error code and error message when api call fails

- tests/other_test.go
> test: update the ignoreupdates list
